export const entities = [
  {
    id: 'manufacturing:work_center',
    label: 'Work Center',
    description: 'A production area where operations are performed.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'manufacturing:machine',
    label: 'Machine',
    description: 'A physical machine or equipment in a work center.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'manufacturing:bom',
    label: 'Bill of Materials',
    description: 'A recipe listing raw materials and operations needed to produce a product.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'manufacturing:production_order',
    label: 'Production Order',
    description: 'An order to produce a specific quantity of a product.',
    labelField: 'orderNumber',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'manufacturing:production_stage',
    label: 'Production Stage',
    description: 'A step in the production process for a production order.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'manufacturing:material_consumption',
    label: 'Material Consumption',
    description: 'Raw material consumption record for a production order.',
    labelField: 'productName',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'manufacturing:quality_inspection',
    label: 'Quality Inspection',
    description: 'Quality control inspection record.',
    labelField: 'inspectionNumber',
    showInSidebar: false,
    fields: [],
  },
]

export default entities
