import type { NotificationTypeDefinition } from '@wantace/shared/modules/notifications'

export const notificationTypes: NotificationTypeDefinition[] = [
  {
    type: 'manufacturing.production_order.new_order',
    module: 'manufacturing',
    titleKey: 'manufacturing.notifications.newOrder.title',
    bodyKey: 'manufacturing.notifications.newOrder.body',
    icon: 'clipboard-list',
    severity: 'info',
    actions: [
      {
        id: 'view-order',
        labelKey: 'manufacturing.notifications.newOrder.viewOrder',
        variant: 'outline',
        href: '/backend/sales/orders/{sourceEntityId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/sales/orders/{sourceEntityId}',
    expiresAfterHours: 72,
  },
  {
    type: 'manufacturing.production_order.materials_short',
    module: 'manufacturing',
    titleKey: 'manufacturing.notifications.materialsShort.title',
    bodyKey: 'manufacturing.notifications.materialsShort.body',
    icon: 'alert-triangle',
    severity: 'warning',
    actions: [
      {
        id: 'view-production-order',
        labelKey: 'manufacturing.notifications.materialsShort.viewProductionOrder',
        variant: 'outline',
        href: '/backend/manufacturing/production-orders/{sourceEntityId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/manufacturing/production-orders/{sourceEntityId}',
    expiresAfterHours: 72,
  },
  {
    type: 'manufacturing.production_order.materials_ready',
    module: 'manufacturing',
    titleKey: 'manufacturing.notifications.materialsReady.title',
    bodyKey: 'manufacturing.notifications.materialsReady.body',
    icon: 'check-circle',
    severity: 'success',
    actions: [
      {
        id: 'view-production-order',
        labelKey: 'manufacturing.notifications.materialsReady.viewProductionOrder',
        variant: 'outline',
        href: '/backend/manufacturing/production-orders/{sourceEntityId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/manufacturing/production-orders/{sourceEntityId}',
    expiresAfterHours: 48,
  },
  {
    type: 'manufacturing.production_order.stage_completed',
    module: 'manufacturing',
    titleKey: 'manufacturing.notifications.stageCompleted.title',
    bodyKey: 'manufacturing.notifications.stageCompleted.body',
    icon: 'check-square',
    severity: 'info',
    actions: [
      {
        id: 'view-production-order',
        labelKey: 'manufacturing.notifications.stageCompleted.viewProductionOrder',
        variant: 'outline',
        href: '/backend/manufacturing/production-orders/{sourceEntityId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/manufacturing/production-orders/{sourceEntityId}',
    expiresAfterHours: 48,
  },
  {
    type: 'manufacturing.production_order.production_completed',
    module: 'manufacturing',
    titleKey: 'manufacturing.notifications.productionCompleted.title',
    bodyKey: 'manufacturing.notifications.productionCompleted.body',
    icon: 'package-check',
    severity: 'success',
    actions: [
      {
        id: 'view-production-order',
        labelKey: 'manufacturing.notifications.productionCompleted.viewProductionOrder',
        variant: 'outline',
        href: '/backend/manufacturing/production-orders/{sourceEntityId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/manufacturing/production-orders/{sourceEntityId}',
    expiresAfterHours: 48,
  },
  {
    type: 'manufacturing.quality_inspection.passed',
    module: 'manufacturing',
    titleKey: 'manufacturing.notifications.qcPassed.title',
    bodyKey: 'manufacturing.notifications.qcPassed.body',
    icon: 'badge-check',
    severity: 'success',
    actions: [
      {
        id: 'view-production-order',
        labelKey: 'manufacturing.notifications.qcPassed.viewProductionOrder',
        variant: 'outline',
        href: '/backend/manufacturing/production-orders/{sourceEntityId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/manufacturing/production-orders/{sourceEntityId}',
    expiresAfterHours: 72,
  },
  {
    type: 'manufacturing.quality_inspection.failed',
    module: 'manufacturing',
    titleKey: 'manufacturing.notifications.qcFailed.title',
    bodyKey: 'manufacturing.notifications.qcFailed.body',
    icon: 'x-circle',
    severity: 'error',
    actions: [
      {
        id: 'view-production-order',
        labelKey: 'manufacturing.notifications.qcFailed.viewProductionOrder',
        variant: 'outline',
        href: '/backend/manufacturing/production-orders/{sourceEntityId}',
        icon: 'external-link',
      },
      {
        id: 'view-inspection',
        labelKey: 'manufacturing.notifications.qcFailed.viewInspection',
        variant: 'outline',
        href: '/backend/manufacturing/quality-inspections/{sourceEntityId}',
        icon: 'clipboard-check',
      },
    ],
    linkHref: '/backend/manufacturing/production-orders/{sourceEntityId}',
    expiresAfterHours: 72,
  },
]

export default notificationTypes
